#!/usr/bin/env python
"""
Unit tests for run_compute_precision_recall.py
==============================================
"""


from unittest import TestCase, main
import re
from subprocess import Popen, PIPE
from os import close, walk, remove, environ, rename, makedirs
from os.path import (abspath, exists, getsize, join,
                     dirname, splitext, basename)
from tempfile import mkstemp, mkdtemp
from shutil import rmtree
from StringIO import StringIO

from skbio.parse.sequences import parse_fasta
from skbio.util import remove_files

from run_compute_precision_recall import (graph_abundance_func,
                                          compute_fp_other)

# ----------------------------------------------------------------------------
# Copyright (c) 2015--, Evguenia Kopylova
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file COPYING.txt, distributed with this software.
# ----------------------------------------------------------------------------


# Test class and cases
class ComputePrecisionRecall(TestCase):
    """ Tests for run_compute_precision_recall.py functionality """

    def setUp(self):
        """ This setup uses QIIME's pick_de_novo_otus.py to cluster
            temporary sequences using swarm and assign taxonomy using
            RDP. The 'pick_otus_reference_seqs_fp' and
            'assign_taxonomy_id_to_taxonomy_fp' fields in the QIIME
            config should be set to Greengenes 97% OTUs (version 13.8)
            for the taxonomy to be assigned as expected.
        """
        self.results_dir = mkdtemp()
        # to store program results
        self.output_dir = join(self.results_dir, "16S", "de_novo")
        makedirs(self.output_dir)
        # to store output results of filter OTUs from table 
        self.filter_dir = join(self.results_dir, "filter_table", "16S", "de_novo")
        makedirs(self.filter_dir)
        # to store precision / recall results
        self.precision_dir = join(self.results_dir, "precision")
        makedirs(self.precision_dir)

        print "self.results_dir = ", self.results_dir

        # create temporary file with read sequences defined in seqs
        f, self.seqs = mkstemp(prefix='temp_reads_',
                               suffix='.fasta')
        close(f)

        # write read sequences to tmp file
        with open(self.seqs, 'w') as tmp:
            tmp.write(seqs)

        # create temporary params file
        f, self.params = mkstemp(prefix='temp_params_',
                                 suffix='.txt')
        close(f)

        # write read sequences to tmp file
        with open(self.params, 'w') as tmp:
            tmp.write(params)

        # blast database
        f, self.blast_nt_db = mkstemp(prefix='blast_nt_',
                                      suffix='.fasta')
        close(f)

        # write read sequences to tmp file
        with open(self.blast_nt_db, 'w') as tmp:
            tmp.write(blast_nt_db)

        # run pick_de_novo_otus.py using swarm
        pick_de_novo_otus_command = ["pick_de_novo_otus.py",    
                                     "-i", self.seqs,
                                     "-p", self.params,
                                     "-o", join(self.output_dir, "swarm_test")]

        proc = Popen(pick_de_novo_otus_command,
                     stdout=PIPE,
                     stderr=PIPE,
                     close_fds=True)
        proc.wait()
        stdout, stderr = proc.communicate()

        results_otus = join(
            self.output_dir, "swarm_test", "swarm_picked_otus", "%s_otus.txt" % splitext(basename(self.seqs))[0])
        rename_otus = join(
            self.output_dir, "swarm_test", "swarm_picked_otus", "seqs_otus.txt")

        rename(results_otus, rename_otus)

        # list of files to remove
        self.files_to_remove = [self.seqs, self.params]

    def tearDown(self):
    	#remove_files(self.files_to_remove)
        #rmtree(self.results_dir)
        pass

    def test_graph_abundance_func(self):
        """ Verify the correctness of graph_abundance_func() functionality
            using known TP and FP taxa.
        """
        # True positive taxonomies at genus level
        true_positive_otus = {'k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Ruminococcaceae;g__Ruminococcus': ['denovo15',
                              'denovo9', 'denovo2'],
                              'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacteriales;f__Enterobacteriaceae;g__Providencia': ['denovo3'],
                              'k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Lachnospiraceae;g__Dorea': ['denovo14', 'denovo6', 'denovo1',
                              'denovo10']}

        # False positive taxonomies for which all OTUs are chimeric
        false_positive_chimeric_otus = {'k__Bacteria;p__Firmicutes;c__Bacilli': ['denovo19'],
                                        'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria': ['denovo16', 'denovo0', 'denovo18']}

        # False positive taxonomies for which all OTUs are not chimeric
        # and map to Blast's NT database with >=97% id and coverage
        false_positive_known_otus = {'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Moraxellaceae;g__Acinetobacter': ['denovo4'],
                                     'k__Bacteria;p__Lentisphaerae;c__[Lentisphaeria];o__Victivallales;f__Victivallaceae;g__Victivallis': ['denovo5', 'denovo7']}

        # False positive taxonomies for which all OTUs are not chimeric
        # and do not map to Blast's NT database with >=97% id and coverage
        false_positive_other_otus = {'k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales': ['denovo13', 'denovo17', 'denovo8', 'denovo12', 'denovo11']}

        taxonomy_mean = {}
        taxonomy_stdev = {}

        graph_abundance_func(true_positive_otus,
                             false_positive_known_otus,
                             false_positive_other_otus,
							 false_positive_chimeric_otus,
                             "16S",
                             "swarm",
                             "test",
                             "de_novo",
                             self.results_dir,
                             taxonomy_mean,
                             taxonomy_stdev)

        taxonomy_mean_expected =  {'swarm': [8.0, 5.0, 11.0, 5.0]}
        taxonomy_stdev_expected =  {'swarm': [3.0, 1.0, 0.0, 3.0]}

        self.assertEqual(taxonomy_mean_expected, taxonomy_mean)
        self.assertEqual(taxonomy_stdev_expected, taxonomy_stdev)


    def test_compute_fp_other(self):
        """ Test compute_fp_other function
        """

        expected_tax = set(['k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Ruminococcaceae;g__Ruminococcus',
                            'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacteriales;f__Enterobacteriaceae;g__Providencia',
                            'k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Lachnospiraceae;g__Dorea'])

        actual_tax = set(['k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Ruminococcaceae;g__Ruminococcus',
                          'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacteriales;f__Enterobacteriaceae;g__Providencia',
                          'k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Lachnospiraceae;g__Dorea',
                          'k__Bacteria;p__Firmicutes;c__Bacilli',
                          'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria',
                          'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Moraxellaceae;g__Acinetobacter',
                          'k__Bacteria;p__Lentisphaerae;c__[Lentisphaeria];o__Victivallales;f__Victivallaceae;g__Victivallis',
                          'k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales'])

        chimera_db_16S_fp = StringIO(chimera_db_16S)
        taxonomy_mean = {}
        taxonomy_stdev = {}

        # build blast index
        blast_db_command = ["makeblastdb",    
                            "-in", self.blast_nt_db,
                            "-out", join(self.results_dir, "nt"),
                            "-dbtype", "nucl",
                            "-parse_seqids"]

        proc = Popen(blast_db_command,
                     stdout=PIPE,
                     stderr=PIPE,
                     close_fds=True)
        proc.wait()
        stdout, stderr = proc.communicate()


        fp_chimera, fp_known, fp_other = compute_fp_other(self.results_dir,
            self.precision_dir,
            self.filter_dir,
            taxonomy_mean,
            taxonomy_stdev,
            join(self.results_dir, "nt"),
            actual_tax,
            expected_tax,
            "swarm",
            "test",
            "16S",
            "de_novo",
            "L6",
            chimera_db_16S_fp,
            "1")

        print "fp_chimera = ", fp_chimera
        print "fp_known = ", fp_known
        print "fp_other = ", fp_other


seqs = """>MockMiSeq.even.673461_41582 M00181:51:000000000-A0LUP:1:2:14492:25221 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGAGCGAGCGTTGTCCGGATTTACTGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGGG
>MockMiSeq.even.673461_84993 M00181:51:000000000-A0LUP:1:4:16307:27613 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGAGCGAGCGTTGTCCGGATTTACTGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGGG
>MockMiSeq.even.673461_88807 M00181:51:000000000-A0LUP:1:5:6245:7857 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
CACGTAGGTCACAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGG
>MockMiSeq.even.673461_2216 M00181:51:000000000-A0LUP:1:1:19424:6052 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
CACGTAGGTCACAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCCG
>MockMiSeq.even.673461_634 M00181:51:000000000-A0LUP:1:1:11590:3528 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGAGCGAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGG
>MockMiSeq.even.673461_1009 M00181:51:000000000-A0LUP:1:1:11999:4149 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGAGCGAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGG
>MockMiSeq.even.673461_1112 M00181:51:000000000-A0LUP:1:1:18445:4329 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGAGCGAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGG
>MockMiSeq.even.673461_1481 M00181:51:000000000-A0LUP:1:1:12099:4957 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGAGCGAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGG
>MockMiSeq.even.673461_25361 M00181:51:000000000-A0LUP:1:2:26109:7570 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTAATTAAGTTAGATGTGAAATCCCCGGGCTTAACCTGGGAATGGCATCTAAGACTGGTTAGCTAGAGTCTTGTAGAGGGGGGTAGAATTCCATG
>MockMiSeq.even.673461_25373 M00181:51:000000000-A0LUP:1:2:26122:7584 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTAATTAAGTTAGATGTGAAATCCCCGGGCTTAACCTGGGAATGGCATCTAAGACTGGTTAGCTAGAGTCTTGTAGAGGGGGGTAGAATTCCATG
>MockMiSeq.even.673461_34458 M00181:51:000000000-A0LUP:1:2:21435:17184 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTAATTAAGTTAGATGTGAAATCCCCGGGCTTAACCTGGGAATGGCATCTAAGACTGGTTAGCTAGAGTCTTGTAGAGGGGGGTAGAATTCCATG
>MockMiSeq.even.673461_35596 M00181:51:000000000-A0LUP:1:2:19934:18306 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTAATTAAGTTAGATGTGAAATCCCCGGGCTTAACCTGGGAATGGCATCTAAGACTGGTTAGCTAGAGTCTTGTAGAGGGGGGTAGAATTCCATG
>MockMiSeq.even.673461_53455 M00181:51:000000000-A0LUP:1:3:22885:14823 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCATGGCAAGCCAGATGTGAAAGGCATGGGCTCAACCTGTGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGAGAGGTAAGTGGAATTCCTAG
>MockMiSeq.even.673461_186323 M00181:51:000000000-A0LUP:1:9:15662:24333 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCATGGCAAGCCAGATGTGAAAGGCATGGGCTCAACCTGTGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGAGAGGTAAGTGGAATTCCTAG
>MockMiSeq.even.673461_87316 M00181:51:000000000-A0LUP:1:5:12190:5998 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGCAAGTCTGAAGTGAAAGGCATGGGCTCAACCTGTGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGGGAGGGAAGTGGGAATTCTAG
>MockMiSeq.even.673461_171370 M00181:51:000000000-A0LUP:1:9:22543:7919 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGCAAGTCTGAAGTGAAAGGCATGGGCTCAACCTGTGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGGGAGGGAAGTGGGAATTCTAG
>MockMiSeq.even.673461_28777 M00181:51:000000000-A0LUP:1:2:15970:11304 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGCAAGTCTGAAGTGAAAGGCATGGGCTCAACCTGTGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGGGAGGTAAGTGGGAATTCTAG
>MockMiSeq.even.673461_32563 M00181:51:000000000-A0LUP:1:2:28317:15229 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGTAAGTCTGAAGTGAAAGCCCGGGGCTCAACCCCGGGACTGCTTTGGAAACTATGCAGCTAGAGTGCAGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_46485 M00181:51:000000000-A0LUP:1:3:14602:7541 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGTAAGTCTGAAGTGAAAGCCCGGGGCTCAACCCCGGGACTGCTTTGGAAACTATGCAGCTAGAGTGCAGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_249529 M00181:51:000000000-A0LUP:1:12:20854:26355 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGTAAGTCTGAAGTGAAAGCCCGGGGCTCAACCCCGGGACTGCTTTGGAAACTATGCAGCTAGAGTGCAGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_163017 M00181:51:000000000-A0LUP:1:8:14066:21069 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGTAAGTCTGAAGTGAAAGCCCGGGGCTCAACCCCGGGACTGCTTTGGGAACTATGCAGCTAGAGTGCAGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_65623 M00181:51:000000000-A0LUP:1:4:15088:4441 1:N:0:0 orig_bc=ATCTGCCTGGGA new_bc=ATCTGCCTGGAA bc_diffs=1
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGCAAGTCTGAAGTGAAAGCCCGGGGCTCAACCTCGGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGAGAGGTAAGTGGAATTCCCAG
>MockMiSeq.even.673461_152618 M00181:51:000000000-A0LUP:1:8:26567:10271 1:N:0:0 orig_bc=ATCTGCCTCGAA new_bc=ATCTGCCTGGAA bc_diffs=1
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGCAAGTCTGAAGTGAAAGCCCGGGGCTCAACCGCGGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGAGAGGTAAGTGGAATTCCCAG
>MockMiSeq.even.673461_159025 M00181:51:000000000-A0LUP:1:8:12296:16804 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACAGAGGTCTCAAGCGTTGTTCGGAATCACTGGGCGTAAAGCGTGCGTAGGCTGTTTCGTAAGTCGTGTGTGAAAGGCAGTGGCTTAACCATTGTTCGCTTTGGAAACTGTTAGACTTGAGTGCAGAAGGGGAGAGTGGAATTCCATGT
>MockMiSeq.even.673461_246660 M00181:51:000000000-A0LUP:1:12:8203:22407 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACAGAGGTCTCAAGCGTTGTTCGGAATCACTGGGCGTAAAGCGTGCGTAGGCTGTTTCGTAAGTCGTGTGTGAAAGGCAGTGGCTTAACCATTGTTCGCTTTGGAAACTGTTAGACTTGAGTGCAGAAGGGGAGAGTGGAATTCCATGT
>MockMiSeq.even.673461_38842 M00181:51:000000000-A0LUP:1:2:18682:21744 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATTTGGAACTGTCAGGCTAGAGTGTCGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_231002 M00181:51:000000000-A0LUP:1:12:17567:4860 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATTTGGAACTGTCAGGCTAGAGTGTCGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_6423 M00181:51:000000000-A0LUP:1:1:8558:10853 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCCGGGCTTAACCTGGGGGCTGCATTCCAAACTGGATATCTAGAGTGCAGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_17677 M00181:51:000000000-A0LUP:1:1:15623:22104 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCCGGGCTTAACCTGGGGGCTGCATTCCAAACTGGATATCTAGAGTGCAGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_66033 M00181:51:000000000-A0LUP:1:4:9220:5129 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTCAGGTCGGATGTGAAATCCCCGGGCTTAACCTGGGGGCTGCATTCCAAACTGGATATCTAGAGTGCAGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_184838 M00181:51:000000000-A0LUP:1:9:17875:22448 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTCAAGTGGGATGTGAAATCCCCGGGCTTAACCTGGGGGCTGCATTCCAAACTGGATATCTAGAGTGCAGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_18289 M00181:51:000000000-A0LUP:1:1:7995:22792 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGTGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGAGAGGTAAGTGGAATTCCTAG
>MockMiSeq.even.673461_190870 M00181:51:000000000-A0LUP:1:10:7829:6509 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGTGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGAGAGGTAAGTGGAATTCCTAG
>MockMiSeq.even.673461_1926 M00181:51:000000000-A0LUP:1:1:20987:5633 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACAGAGGGTGCGAGCGTTAATCGGATTTACTGGGCGTAAAGCGTGCGTAGGCGGCTTTTTAAGTCGGATGTGAAATCCCCGAGCTTAACTTGGGAATTGCATTCGATACTGGGAAGCTAGAGTATGGGAGAGGATGGTAGAATTCCAGG
>MockMiSeq.even.673461_2041 M00181:51:000000000-A0LUP:1:1:21173:5797 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACAGAGGGTGCGAGCGTTAATCGGATTTACTGGGCGTAAAGCGTGCGTAGGCGGCTTTTTAAGTCGGATGTGAAATCCCCGAGCTTAACTTGGGAATTGCATTCGATACTGGGAAGCTAGAGTATGGGAGAGGATGGTAGAATTCCAGG
>MockMiSeq.even.673461_5034 M00181:51:000000000-A0LUP:1:1:11118:9451 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACAGAGGGTGCGAGCGTTAATCGGATTTACTGGGCGTAAAGCGTGCGTAGGCGGCTTTTTAAGTCGGATGTGAAATCCCCGAGCTTAACTTGGGAATTGCATTCGATACTGGGAAGCTAGAGTATGGGAGAGGATGGTAGAATTCCAGG
>MockMiSeq.even.673461_6443 M00181:51:000000000-A0LUP:1:1:24352:10870 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACAGAGGGTGCGAGCGTTAATCGGATTTACTGGGCGTAAAGCGTGCGTAGGCGGCTTTTTAAGTCGGATGTGAAATCCCCGAGCTTAACTTGGGAATTGCATTCGATACTGGGAAGCTAGAGTATGGGAGAGGATGGTAGAATTCCAGG
>MockMiSeq.even.673461_74784 M00181:51:000000000-A0LUP:1:4:4166:15150 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
AACGTAGGGTGCAAGCGTTGTTCGGATTTATTGGGCGTAAAGGGTCTGTAGGAGGTTTGTTAAATACGAGGTGAAATCCGGGGGCTCAACTTCCGAATTGCCTTGTAGACTGATGAACTAGAGTACTGGAGAGGTAAGCGGAATACCAGG
>MockMiSeq.even.673461_74575 M00181:51:000000000-A0LUP:1:4:17570:14946 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGTGCAAGCGTTGTTCGGATTTATTGGGCGTAAAGGGTCTGTAGGAGGTTTGTTAAATACGAGGTGAAATCCGGGGGCTCAACTTCCGAATTGCCTTGTAGACTGATGAACTAGAGTACTGGAGAGGTAAGCGGAATACCAGG
>MockMiSeq.even.673461_53430 M00181:51:000000000-A0LUP:1:3:23826:14795 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGAGCAAGCGTTGTTCGGATTTATTGGGCGTAAAGGGTCTGTAGGAGGTTTGTTAAATACGAGGTGAAATCCGGGGGCTCAACTTCCGAATTGCCTTGTAGACTGATGAACTAGAGTACTGGAGAGGTAAGCGGAATACCAGG
>MockMiSeq.even.673461_8547 M00181:51:000000000-A0LUP:1:1:12818:12932 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGTGGCGAGCGTTGTTCGGATTTATTGGGCGTAAAGGGTCTGTAGGAGGTTTGTTAAATACGAGGTGAAATCCGGGGGCTCAACTTCCGAATTGCCTTGTAGACTGATGAACTAGAGTACTGGAGAGGTAAGCGGAATACCAGG
>MockMiSeq.even.673461_10065 M00181:51:000000000-A0LUP:1:1:22868:14345 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGTGGCGAGCGTTGTTCGGATTTATTGGGCGTAAAGGGTCTGTAGGAGGTTTGTTAAATACGAGGTGAAATCCGGGGGCTCAACTTCCGAATTGCCTTGTAGACTGATGAACTAGAGTACTGGAGAGGTAAGCGGAATACCAGG
>MockMiSeq.even.673461_11006 M00181:51:000000000-A0LUP:1:1:17661:15319 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGTGGCGAGCGTTGTTCGGATTTATTGGGCGTAAAGGGTCTGTAGGAGGTTTGTTAAATACGAGGTGAAATCCGGGGGCTCAACTTCCGAATTGCCTTGTAGACTGATGAACTAGAGTACTGGAGAGGTAAGCGGAATACCAGG
>MockMiSeq.even.673461_210939 M00181:51:000000000-A0LUP:1:11:14169:5669 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGCGTAAAGGGAGCGTAGACGGCATGGCAAGCCAGATGTGAAAGCCCCGGGCTCAACCCCGGGACTGCATTTCGAACTGGCAAGCTAGAGTGTCGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_186909 M00181:51:000000000-A0LUP:1:9:21496:25126 1:N:0:0 orig_bc=ATCTGCCCGGAA new_bc=ATCTGCCTGGAA bc_diffs=1
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGCGTAAAGGGAGCGTAGACGGCATGGCAAGCCAGATGTGAAAGCCCCGGGCTCAACCCCGGGGCTGCATTTCGAACTGGCAAGCTAGAGTGTCGGAGAGGAAAGCGGAATTCCTAG
>MockMiSeq.even.673461_189556 M00181:51:000000000-A0LUP:1:10:24207:4457 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGGGCAAGCGTTATCCGGATTTCCTTTTTTTCCCGGGAGCGTAGACGGCACGGCAAGCCAGATGTGAAAGCCCGGGGCTCAACCCCGGTCCTGCATTTGGAACTGCTGAGCTAGAGTTGTGGAGAGGCACGGAGAATTCCTAG
>MockMiSeq.even.673461_190261 M00181:51:000000000-A0LUP:1:10:25706:5633 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTAGGGGGCAAGCGTTATCCGGATTTCCTTTTTTTCCCGGGAGCGTAGACGGCACGGCAAGCCAGATGTGAAAGCCCGGGGCTCAACCCCGGTCCTGCATTTGGAACTGCTGAGCTAGAGTTGTGGAGAGGCACGGAGAATTCCTAG
>MockMiSeq.even.673461_38935 M00181:51:000000000-A0LUP:1:2:17291:21871 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGATCCGAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGG
>MockMiSeq.even.673461_118958 M00181:51:000000000-A0LUP:1:6:9706:18382 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGATCCGAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGG
>MockMiSeq.even.673461_181069 M00181:51:000000000-A0LUP:1:9:26156:18158 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGGAGGATCCGAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCGTGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGGAATTCCCGG
>MockMiSeq.even.673461_36613 M00181:51:000000000-A0LUP:1:2:28963:19290 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTATGGCGCAAGCGTTATCCGGATTTACTGGGCGTAAAGGGCGTGTAGGCGGCCATGCAAGTCAGAAGTGAAAATCCGGGGCTCAACCCCGGAACTGCTTTTGAAACTGTAAAGCTGGAGTGCAGGAGGGGTGAGTGGAATTCCTAG
>MockMiSeq.even.673461_14266 M00181:51:000000000-A0LUP:1:1:19066:18552 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTATGGAGCAAGCGTTATCCGGATTTACTGGGCGTAAAGGGCGTGTAGGCGGCCATGCAAGTCAGAAGTGAAAATCCGGGGCTCAACCCCGGAACTGCTTTTGAAACTGTAAAGCTGGAGTGCAGGAGGGGTGAGTGGAATTCCTAG
>MockMiSeq.even.673461_57880 M00181:51:000000000-A0LUP:1:3:18016:19202 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTATGGACCGAGCGTTGTCCGGAATCATTGGGCGTAAAGGGTACGTAGGCGGCCTAGTAAGTTAGAAGTTAAAGAATATAGCTCAACTATATAAAGCTTTTCAAACTGCTAGACCTGAGAGATGGGAGGGAAAGTGGAAATTCTAGT
>MockMiSeq.even.673461_219746 M00181:51:000000000-A0LUP:1:11:23232:15649 1:N:0:0 orig_bc=ATCTGCCTGGAA new_bc=ATCTGCCTGGAA bc_diffs=0
TACGTATGGACCGAGCGTTGTCCGGAATCATTGGGCGTAAAGGGTACGTAGGCGGCCTAGTAAGTTAGAAGTTAAAGAATATAGCTCAACTATATAAAGCTTTTCAAACTGCTAGGCCTGAGAGATGGGAGGGAAAGTGGAAATTCTAGT
"""

params = """pick_otus:otu_picking_method swarm
pick_otus:threads 1
assign_taxonomy:assignment_method rdp
assign_taxonomy:rdp_max_memory 4000
"""

chimera_db_16S = """>CS/7000004128189873/Akkermansia muciniphila ATCC BAA-835
AGAGTTTGATTCTGGCTCAGAACGAACGCTGGCGGCGTGGATAAGACATGCAAGTCGAAC
GAGAGAATTGCTAGCTTGCTAATAATTCTCTAGTGGCGCACGGGTGAGTAACACGTGAGT
AACCTGCCCCCGAGAGCGGGATAGCCCTGGGAAACTGGGATTAATACCGCATAGTATCGA
AAGATTAAAGCAGCAATGCGCTTGGGGATGGGCTCGCGGCCTATTAGTTAGTTGGTGAGG
TAACGGCTCACCAAGGCGATGACGGGTAGCCGGTCTGAGAGGATGTCCGGCCACACTGGA
ACTGAGACACGGTCCAGACACCTACGGGTGGCAGCAGTCGAGAATCATTCACAATGGGGG
AAACCCTGATGGTGCGACGCCGCGTGGGGGAATGAAGGTCTTCGGATTGTAAACCCCTGT
CATGTGGGAGCAAATTAAAAAGATAGTACCACAAGAGGAAGAGACGGCTAACTCTGTGCC
AGCAGCCGCGGTAATACAGAGGTCTCAAGCGTTGTTCGGAATCACTGGGCGTAAAGCGTG
CGTAGGCTGTTTCGTAAGTCGTGTGTGAAAGGCGCGGGCTCAACCCGCGGACGGCACATG
ATACTGCGAGACTAGAGTAATGGAGGGGGAACCGGAATTCTCGGTGTAGCAGTGAAATGC
GTAGATATCGAGAGGAACACTCGTGGCGAAGGCGGGTTCCTGGACATTAACTGACGCTGA
GGCACGAAGGCCAGGGGAGCGAAAGGGATTAGATACCCCTGTAGTCCTGGCAGTAAACGG
TGCACGCTTGGTGTGCGGGGAATCGACCCCCTGCGTGCCGGAGCTAACGCGTTAAGCGTG
CCGCCTGGGGAGTACGGTCGCAAGATTAAAACTCAAAGAAATTGACGGGGACCCGCACAA
GCGGTGGAGTATGTGGCTTAATTCGATGCAACGCGAAGAACCTTACCTGGGCTTGACATG
TAATGAACAACATGTGAAAGCATGCGACTCTTCGGAGGCGTTACACAGGTGCTGCATGGC
CGTCGTCAGCTCGTGTCGTGAGATGTTTGGTTAAGTCCAGCAACGAGCGCAACCCCTGTT
GCCAGTTACCAGCACGTGAAGGTGGGGACTCTGGCGAGACTGCCCAGATCAACTGGGAGG
AAGGTGGGGACGACGTCAGGTCAGTATGGCCCTTATGCCCAGGGCTGCACACGTACTACA
ATGCCCAGTACAGAGGGGGCCGAAGCCGCGAGGCGGAGGAAATCCTAAAAACTGGGCCCA
GTTCGGACTGTAGGCTGCAACCCGCCTACACGAAGCCGGAATCGCTAGTAATGGCGCATC
AGCTACGGCGCCGTGAATACGTTCCCGGGTCTTGTACACACCGCCCGTCACATCATGGAA
GCCGGTCGCACCCGAAGTATCTGAAGCCAACCGCAAGGAGGCAGGGTCCTAAGGTGAGAC
TGGTAACTGGGATGAAGTCGTAACAAGGTAGCCGTAGGGGAACCTGCGGCTGGATCACCT
>CS/7000004131501134/Streptococcus infantarius subsp. infantarius ATCC BAA-102
AGAGTTTGATCCTGGCTCAGGACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAAC
GCTGAAAACTTTAGCTTGCTAAAGTTTGAAGAGTTGCGAACGGGTGAGTAACGCGTAGGT
AACCTGCCTACTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCATAACAGCAT
TTAACCCATGTTAGATGCTTGAAAGGAGCAATTGCTTCACTAGTAGATGGACCTGCGTTG
TATTAGCTAGTTGGTGAGGTAACGGCTCACCAAGGCGACGATACATAGCCGACCTGAGAG
GGTGATCGGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTAGG
GAATCTTCGGCAATGGGGGCAACCCTGACCGAGCAACGCCGCGTGAGTGAAGAAGGTTTT
CGGATCGTAAAGCTCTGTTGTAAGAGAAGAACGTGTGTGAGAGTGGAAAGTTCACACAGT
GACGGTAACTTACCAGAAAGGGACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAG
GTCCCGAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTTAATAAGTCT
GAAGTTAAAGGCAGTGGCTTAACCATTGTTCGCTTTGGAAACTGTTAGACTTGAGTGCAG
AAGGGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCG
GTGGCGAAAGCGGCTCTCTGGTCTGTAACTGACGCTGAGGCTCGAAAGCGTGGGGAGCAA
ACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGAGTGCTAGGTGTTAGGCCCT
TTCCGGGGCTTAGTGCCGCAGCTAACGCATTAAGCACTCCGCCTGGGGAGTACGACCGCA
AGGTTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAAT
TCGAAGCAACGCGAAGAACCTTACCAGGTCTTGACATCCCGATGCTATTCCTAGAGATAG
GAAGTTTCTTCGGAACATCGGTGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGA
GATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTATTGTTAGTTGCCATCATTAAGTT
GGGCACTCTAGCGAGACTGCCGGTAATAAACCGGAGGAAGGTGGGGATGACGTCAAATCA
TCATGCCCCTTATGACCTGGGCTACACACGTGCTACAATGGTTGGTACAACGAGTCGCGA
GTCGGTGACGGCAAGCAAATCTCTTAAAGCCAATCTCAGTTCGGATTGTAGGCTGCAACT
CGCCTACATGAAGTCGGAATCGCTAGTAATCGCGGATCAGCACGCCGCGGTGAATACGTT
CCCGGGCCTTGTACACACCGCCCGTCACACCACGAGAGTTTGTAACACCCGAAGTCGGTG
AGGTAACCTTTTAGGAGCCAGCCGCCTAAGGTGGGATAGATGATTGGGGTGAAGTCGTAA
CAAGGTAGCCGTATCGGAAGGTGCGGCTGGATCACCT
>CS/7000004129350417/Enterobacter sakazakii ATCC BAA-894
AGAGTTTGATCATGGCTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAAC
GGTAACAGGGAGCAGCTTGCTGCTCTGCTGACGAGTGGCGGACGGGTGAGTAATGTCTGG
GAAACTGCCTGATGGAGGGGGATAACTACTGGAAACGGTAGCTAATACCGCATAACGTCT
ACGGACCAAAGTGGGGGACCTTCGGGCCTCATGCCATCAGATGTGCCCAGATGGGATTAG
CTAGTAGGTGGGGTAACGGCTCACCTAGGCGACGATCCCTAGCTGGTCTGAGAGGATGAC
CAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATAT
TGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTT
GTAAAGTACTTTCAGCGGGGAGGAAGGCGTTGTGGTTAATAACCGCAGCGATTGACGTTA
CCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAA
GCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTTAAGTCAGATGTGA
AATCCCCGGGCTCAACCTGGGAACTGCATTTGAAACTGGCAGGCTTGAGTCTCGTAGAGG
GGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCG
AAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGA
TTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCGACTTGGAGGTTGTGCCCTTGAGG
CGTGGCTTCCGGAGCTAACGCGTTAAGTCGACCGCCTGGGGAGTACGGCCGCAAGGTTAA
AACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGC
AACGCGAAGAACCTTACCTGGTCTTGACATCCAGAGAATCCTGCAGAGATGCGGGAGTGC
CTTCGGGAACTCTGAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTG
GGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTTGTTGCCAGCGGTTCGGCCGGGAAC
TCAAAGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGATGACGTCAAGTCATCATGG
CCCTTACGACCAGGGCTACACACGTGCTACAATGGCGCATACAAAGAGAAGCGACCTCGC
GAGAGCAAGCGGACCTCATAAAGTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTC
CATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCACGGTGAATACGTTCCCGGG
CCTTGTACACACCGCCCGTCACACCATGGGAGTGGGTTGCAAAAGAAGTAGGTAGCTTAA
CCTTCGGGAGGGCGCTTACCACTTTGTGATTCATGACTGGGGTGAAGTCGTAACAAGGTA
ACCGTAGGGGAACCTGCGGTTGGATCACCT
>CS/7000004130085859/Eubacterium ventriosum ATCC 27560
AGAGTTTGATCCTGGCTCAGGATGAACGCTGGCGGCGTGCTTAATACATGCAAGTCGAAC
GAAGCACCTTGGACAGAATCCTTCGGGAGGAAGACCATTGTGACTGAGTGGCGGACGGGT
GAGTAACGCGTGGGTAACCTGCCTTGTACAGGGGGATAACAGTTGGAAACGACTGCTAAT
ACCGCATAAGCGCACAGTACCGCATGGTACGGTGTGAAAAACTCCGGTGGTACAAGATGG
ACCCGCGTCTGATTAGCTGGTTGGTGAGGTAACGGCCCACCAAGGCGACGATCAGTAGCC
GACTTGAGAGAGTGATCGGCCACATTGGGACTGAGACACGGCCCAAACTCCTACGGGAGG
CAGCAGTAGGGAATATTGCACAATGGGGGAAACCCTGATGCAGCGACGCCGCGTGAAGGA
AGAAGTATTTCGGTATGTAAACTTCTATCAGCAAGGAAGAAAATGACGGTACTTGACTAA
GAAGCCCCGGCTAAATACGTGCCAGCAGCCGCGGTAATACGTATGGGGCAAGCGTTATCC
GGATTTACTGGGTGTAAAGGGAGCGTAGGCGGCATGGCAAGTCAGAAGTGAAAGCCTGGG
GCTCAACCCCGGAATTGCTTTTGAAACTGTCAGGCTAGAGTGTCGGAGGGGTAAGCGGAA
TTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCGGTGGCGAAGGCGGCT
TACTGGACGATTACTGACGCTGAGGCTCGAAAGCGTGGGGAGCAAACAGGATTAGATACC
CTGGTAGTCCACGCCGTAAACGATGAATACTAGGTGTCGGGGGACAATAGTTCCTCGGTG
CCGAAGCAAACGCATTAAGTATTCCACCTGGGGAGTACGTTCGCAAGAATGAAACTCAAA
GGAATTGACGGGGACCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCAACGCGAA
GAACCTTACCTGCTCTTGACATCCCACTGACAGGTCAGTAATGTGACCCTTTCTTCGGAA
CAGTGGAGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGT
CCCGCAACGAGCGCAACCCTTGTCTTTAGTAGCCAGCAGTACGGCTGGGCACTCTAGAGA
GACTGCCAGGGATAACCTGGAGGAAGGCGGGGATGACGTCAAATCATCATGCCCCTTACG
AGCAGGGCTACACACGTGCTACAATGGCGTAAACAAAGGGAAGCGACCCCGTGAGGGTAA
GCAAATCTCAAAAATAACGTCTCAGTTCGGATTGTAGTCTGCAACTCGACTACATGAAGC
TGGAATCGCTAGTAATCGCGAATCAGAATGTCGCGGTGAATACGTTCCCGGGTCTTGTAC
ACACCGCCCGTCACACCATGGGAGTTGGATATGCCCGAAGTCAGTGACCCAACCGTAAGG
AGGGAGCTGCCGAAGGTGGAGCCGATAACTGGGGTGAAGTCGTAACAAGGTAGCCGTATC
GGAAGGTGCGGCTGGATCACCT
>CS/S000003122/Klebsiella pneumoniae subsp. ozaenae (T)
TGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAGCGGTAGCACAGAGAGCTTGCTCT
CGGGTGACGAGCGGCGGACGGGTGAGTAATGTCTGGGAAACTGCCTGATGGAGGGGGATA
ACTACTGGAAACGGTAGCTAATACCGCATAACGTCGCAAGACCAAAGTGGGGGACCTTCG
GGCCTCATGCCATCAGATGTGCCCAGATGGGATTAGCTAGTAGGTGGGGTAACGGCTCAC
CTAGGCGACGATCCCTAGCTGGTCTGAGAGGATGACCAGCCACACTGGAACTGAGACACG
GTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATG
CAGCCATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCACTTTCAGYGGGGAGGA
AGGCGWTAAGGTTAATAACCTTGKCGATTGACGTTACCCGCAGAAGAAGCACCGGCTAAC
TCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGT
AAAGCGCACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCCGGGCTTAACCTGGGAAC
TGCATTCGAAACTGGCAGGCTAGAGTCTTGTAGAGGGGGGTAGAATTCCAGGTGTAGCGG
TGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAAAGACT
GACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCC
GTAAACGATGTCGATTTGGAGGTTGTGCCCTTGAGGCGTGGCTTCCGGAGCTAACGCGTT
AAATCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCC
CGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCTGGTCT
TGACATCCACAGAACTTTCCAGAGATGGATTGGTGCCTTCGGGAACTGTGAGACAGGTGC
TGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAA
CCCTTATCCTTTGTTGCCAGCGGTCCGGCCGGGAACTCAAAGGAGACTGCCAGTGATAAA
CTGGAGGAAGGTGGGGATGACGTCAAGTCATCATGGCCCTTACGACCAGGGCTACACACG
TGCTACAATGGCATATACAAAGAGAAGCGACCTCGCGAGAGCAAGCGGACCTCATAAAGT
ATGTCGTAGTCCGGATTGGAGTCTGCAACTYGACTCCATGAAGTCGGAATCGCTAGTAAT
CGTAGATCAGAATGCTACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACAC
CATGGGAGTGGGTTGCAAAAGAAGTAGGTAGCTTAACCTTCGGGAGGGCGCTTACCACTT
TGTGATTCATGA
>CS/7000004128490803/Clostridium botulinum Bf
AGAGTTTGATCCTGGCTCAGGACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAGC
GATGAAACTTCCTTCGGGAAGTGGATTAGCGGCGGACGGGTGAGTAACACGTGGGTAACC
TGCCTCAAAGTGGGGGATAGCCTTCCGAAAGGAAGATTAATACCGCATAATATGAGAGAA
TCGCATGATTTTCTTATCAAAGATTTATTGCTTTGAGATGGACCCGCGGCGCATTAGCTA
GTTGGTAAGGTAACGGCTTACCAAAGGCAACGATGCGTAGCCGACCTGAGAGGGTGATCG
GCCACATTGGAACTGAGACACGGTCCAGACTCCTACGGAGGCAGCAGTGGGGATATTGCG
CAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGGGTGATGAAGGTCTTCGGATTGTAA
AGCCCTGTTTTCTAGGACGATAATGACGGTACTAGAGGAGGAAGCCACGGCTAACTACGT
GCCAGCAGCCGCGGTAATACGTAGGTGGCGAGCGTTGTCCGGATTTACTGGGCGTAAAGG
GTGCGTAGGCGGATGTTTAAGTGGGATGTGAAATCCCCGGGCTTAACCTGGGGGCTGCAT
TCCAAACTGGATATCTAGAGTGCAGGAGAGGAAAGCGGAATTCCTAGTGTAGCGGTGAAA
TGCGTAGAGATTAGGAAGAACACCAGTGGCGAAGGCGGCTTTCTGGACTGTAACTGACGC
TGAGGCACGAAAGCGTGGGTAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAA
CGATGGATACTAGGTGTAGGGGGTATCAACTCCCCCCTGTGCCGCAGTTAACACAATAAG
TATCCCGCCTGGGGAGTACGGTCGCAAGATTAAAACTCAAAGGAATTGACGGGGGCCCGC
ACAAGCAGCGGAGCATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCTGGACTTGA
CATCCCTTGCATAGCCTAGAGATAGGTGAAGCCCTTCGGGGCAAGGAGACAGGTGGTGCA
TGGTTGTCGTCAGCTCGTGTCGTGAGATGTTAGGTTAAGTCCTGCAACGAGCGCAACCCT
TGTTATTAGTTGCTACCATTAAGTTGAGCACTCTAATGAGACTGCCTGGGTAACCAGGAG
GAAGGTGGGGATGACGTCAAATCATCATGCCCCTTATGTCCAGGGCTACACACGTGCTAC
AATGGTAGGTACAATAAGACGCAAGACCGTGAGGTGGAGCAAAACTTATAAAACCTATCT
CAGTTCGGATTGTAGGCTGCAACTCGCCTACATGAAGCTGGAGTTGCTAGTAATCGCGAA
TCAGAATGTCGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGAG
AGCTGGTAACTACCCGAAGTCCGTGAGGTAACCGTAAGGAACCAGCGGCCGAAGGTGGGA
TTAGTGATTGGGGTGAAGTCGTAACTAAGGTAGCCGTAGGAGAACCTGCGGCTGGATCAC
CT
>CS/7000004131499453/Salmonella enterica subsp. enterica serovar Kentucky str. CVM29188
AGAGTTTGATCATGGCTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAAC
GGTAGCACAGAGAGCTTGCTCTCGGGTGACGAGTGGCGGACGGGTGAGTAATGTCTGGGA
AACTGCCCGATGGAGGGGGATAACTACTGGAAACGGTAGCTAATACCGCATAACGTCGCA
AGACCAAAGTGGGGGACCTTCGGGCCTCACACCATCGGATGTGCCCAGATGGGATTAGCT
AGTAGGTGGGGTAACGGCTCACCTAGGCGACGATCCCTAGCTGGTCTGAGAGGATGACCA
GCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTG
CACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGT
AAAGTACTTTCAGCGAGGAGGAAGGCGTTGTGGTTAATAACCACAGCGATTGACGTTACT
CGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGC
GTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAA
TCCCCGGGCTCAACCTGGGAACTGCATTTGAAACTGGCAAGCTTGAGTCTCGTAGAGGGG
GGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAA
GGCGGCCCCCTGGACAAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATT
AGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGCCCTTGAGGCG
TGGCTTCCGGAGCTAACGCGTTAAGTAGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAA
CTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAA
CGCGAAGAACCTTACCTGGTCTTGACATCCACGGAAGTTTTCAGAGATGAGAATGTGCCT
TCGGGAACCGTGAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGG
TTAAGTCCCGCAACGAGCGCAACCCTTATCCTTTGTTGCCAGCGGTTAGGCCGGGAACTC
AAAGGAGACTGCCAGTGATAAACTGGAGGAAGGTGGGGATGACGTCAAGTCATCATGGCC
CTTACGACCAGGGCTACACACGTGCTACAATGGCGCATACAAAGAGAAGCGACCTCGCGA
GAGCAAGCGGACCTCATAAAGTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTCCA
TGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCACGGTGAATACGTTCCCGGGCC
TTGTACACACCGCCCGTCACACCATGGGAGTGGGTTGCAAAAGAAGTAGGTAGCTTAACC
TTCGGGAGGGCGCTTACCACTTTGTGATTCATGACTGGGGTGAAGTCGTAACAAGGTAAC
CGTAGGGGAACCTGCGGTTGGATCACCT
>CS/7000004128491900/Coprococcus comes ATCC 27758
AGAGTTTGATCCTGGCTCAGGATGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAAC
GAAGCACTTTAACCTGATTCTTCGGATGAAGGTTTTTGTGACTGAGTGGCGGACGGGTGA
GTAACGCGTGGGTAACCTGCCTCATACAGGGGGATAACAGTTAGAAATGACTGCTAATAC
CGCATAAGACCACAGAGCCGCATGGCTCGGTGGGAAAAACTCCGGTGGTATGAGATGGAC
CCGCGTCTGATTAGGTAGTTGGTGGGGTAACGGCCTACCAAGCCAACGATCAGTAGCCGA
CCTGAGAGGGTGACCGGCCACATTGGGACTGAGACACGGCCCAAACTCCTACGGGAGGCA
GCAGTGGGGAATATTGCACAATGGGGGAAACCCTGATGCAGCGACGCCGCGTGAGCGAAG
AAGTATTTCGGTATGTAAAGCTCTATCAGCAGGGAAGAAAATGACGGTACCTGACTAAGA
AGCACCGGCTAAATACGTGCCAGCAGCCGCGGTAATACGTATGGTGCAAGCGTTATCCGG
ATTTACTGGGTGTAAAGGGAGCGTAGACGGCTGTGTAAGTCTGAAGTGAAAGCCCGGGGC
TCAACCCCGGGACTGCTTTGGAAACTATGCAGCTAGAGTGTCGGAGAGGTAAGTGGAATT
CCCAGTGTAGCGGTGAAATGCGTAGATATTGGGAGGAACACCAGTGGCGAAGGCGGCTTA
CTGGACGATGACTGACGTTGAGGCTCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCT
GGTAGTCCACGCCGTAAACGATGACTACTAGGTGTCGGGGAGCAAAGCTCTTCGGTGCCG
CAGCAAACGCAATAAGTAGTCCACCTGGGGAGTACGTTCGCAAGAATGAAACTCAAAGGA
ATTGACGGGGACCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCAACGCGAAGAA
CCTTACCTGCTCTTGACATCCCGGTGACCGGCGTGTAATGACGCCTTTTCTTCGGAACAC
CGGTGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCC
GCAACGAGCGCAACCCTTATCTTCAGTAGCCAGCAATTCGGATGGGCACTCTGGAGAGAC
TGCCAGGGATAACCTGGAGGAAGGTGGGGATGACGTCAAATCATCATGCCCCTTATGAGC
AGGGCTACACACGTGCTACAATGGCGTAAACAAAGGGAAGCGAGCCTGCGAGGGTAAGCA
AATCTCAAAAATAACGTCTCAGTTCGGATTGTAGTCTGCAACTCGACTACATGAAGCTGG
AATCGCTAGTAATCGCGAATCAGCATGTCGCGGTGAATACGTTCCCGGGTCTTGTACACA
CCGCCCGTCACACCATGGGAGTTGGTAACGCCCGAAGTCAGTGACCCAACCGTAAGGAGG
GAGCTGCCGAAGGTGGGACCGATAACTGGGGTGAAGTCGTAACAAGGTAGCCGTATCGGA
AGGTGCGGCTGGATCACCT
"""

blast_nt_db = """>gi|675822360|gb|KM108538.1| Acinetobacter sp. M.pstv.39.1 16S ribosomal RNA gene, partial sequence
GTCGAGCGAGGGAAGGTTGCTTCGGTAACTGACCTAGCGGCGGACGGGTGAGTAATGCTTAGGAATCTGC
CATTTAGTGGGGGACAACATTCCGAAAGGAATGCTAATACCGCATACGTCCTACGGGAGAAAGCAGGGGA
TCTTCGGACCTTGCGCTAAATGATGAGCCTAAGTCGGATTAGCTAGTTGGTGGGGTAAAGGCCTACCAAG
GCGACGATCTGTAGCGGGTCTGAGAGGATGATCCGCCACACTGGGACTGAGACACGGCCCAGACTCCTAC
GGGAGGCAGCAGTGGGGAATATTGGACAATGGGCGGAAGCCTGATCCAGCCATGCCGCGTGTGTGAAGAA
GGCCTTATGGTTGTAAAGCACTTTAAGCGAGGAGGAGGCTACTTAGATTAATACTCTAGGATAGTGGACG
TTACTCGCAGAATAAGCACCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGTGCGAGCGTTAA
TCGGATTTACTGGGCGTAAAGCGTGCGTAGGCGGCTTTTTAAGTCGGATGTGAAATCCCCGAGCTTAACT
TGGGAATTGCATTCGATACTGGGAAGCTAGAGTATGGGAGAGGATGGTAGAATTCCAGGTGTAGCGGTGA
AATGCGTAGAGATCTGGAGGAATACCGATGGCGAAGGCAGCCATCTGGCCTAATACTGACGCTGAGGTAC
GAAAGCATGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCATGCCGTAAACGATGTCTACTAGCCGTT
GGGGCCTTTGAGGCTTTAGTGCGCAGCTAACGCGATAAGTAGACCGCCTGGGGAGTACGGTCGCAAGACT
AAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGTTTAATTCGATGCAACGCGAAG
AACCTTACCTGGCCTTGA
>gi|645321370|ref|NR_118352.1| Victivallis vadensis strain Cello 16S ribosomal RNA gene, partial sequence
AGGGTTTGATCCTGGCTCAGAACGAACGCTGGCGGCATGGATTAGGCATGCAAGTTGAACGAACTCCTTC
GGGAGTGAGTAGCGAAAGGGTGAGGAACGCGTGAGTAATCTGCCCATAAGTTGGGAACAACAGTTGGAAA
CGACTGCTAATACCGAATGTGGCTATTGACCCGCATGGGTTTTTGGCTAAAGATTTATCGCTTATGGATG
AGCTCGCGTCCCATTAGCTAGTTGGTGAGGTAACGGCCCACCAAGGCTACGATGGGTAGCTGGTCTGAGA
GGATGGTCAGCCACACTGGGACTGAGACACTGCCCAGACTCCTACGGGAGGCTGCAGTCGAGAATCTTGG
GCAATGCGCGAAAGCGTGACCCAGCAATGCCGCGTGCATGATGAAGGCCTCGGGTCGTAAAATGCTGTCT
CCCGTGACGAATAATGACGGTAGCGGGGAAGGAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATA
CGTAGGTGGCGAGCGTTGTTCGGATTTATTGGGCGTAAAGGGTCTGTAGGAGGTTTGTTAAATACGAGGT
GAAATCCGGGGGCTCAACTTCCGAATTGCCTTGTAGACTGATGAACTAGAGTACTGGAGAGGTAAGCGGA
ATACCAGGTGTAGCGGTGGAATGCGTAGATATCTGGTAGAACACCAATAGCGAAGGCAGCTTGCTGGACA
GAAACTGACTCTGAAAGACGAAAGCATGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCATGCCGTAA
ACGTTGTCAACTTGATGTGGGCGGATTTAGTCCTGTCCGTATCGAAGCTAACGCGATAAGTTGACCGCCT
GGGAACTACGGCCGCAAGGCTAAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGG
CTTAATTCGAGGCAACGCGAAGAACCTTACCTGGGCTTGAAATATACCGGACCGGCTGTGAAAGCAGTCT
TCTCTTCGGAGCTGGTATACAGGTGCTGCATGGCTGTCGTCAGCTCGTGCCGTGAGGTGTTCGGTTAAGT
CCGGCAACGAGCGCAACCCGTGTCATTAGTTGCCAACAGGTAATGCTGGGGACTCTAATGAGACTGCCTG
TGTTAAGCAGGAGGAAGGCGCGGATGACGTCAAGTCAGTATGGCCCTTACGCCCAGGGCTGCACACGTGC
TACAATGGGGGGTACAATGAGAAGCGAAGTCGCGAGGCGGAGCAAATCTACAAAACCTCTCTTAGTTCAG
ATTGCAGTCTGCAACTCGACTGCATGAAGTTGGAATCGCTAGTAAATGCGTATCAGCTACGACGCATTGA
ATACGTTCCCGGGCCTTGTACACACCGCCC
>gi|643411510|gb|KF091209.1| Uncultured bacterium clone nck145a07c1 16S ribosomal RNA gene, partial sequence
GATAAACGCTGGCGGCGTGCATAACACATGCAAGTCGAACGATGAAACTTGAATGATTTCTTCGGAATGA
ACTTAAGTGGATTAGTGGCGAACGGGTGAGTAACACGTGAGTAACCTGCCTTACACAAGGGGATAGCCTC
TGGAAACGGAGAATAATACCCTATAAAGTCTAATCAGCACATGCTGGAAAGACCAAAGATTTATCGGTGT
AAGATGGACTTGCGTCTGATTAGCTAGTTGGTGAGATAAAAGCTCACCAAGGCGACGATCAGTAGCCGGC
TTGAGAGAGTGTACGGCCACATTGGGACTGAGACACGGCCCAAACTCCTACGGGAGGCAGCAGTGGGGAA
TTTTGCACAATGGGGGGAACCCTGATGCAGCGACGCCGCGTGATTTAGAAGGCCTTCGGGTTGTAAAAAT
CTTTTTTACGGGATGAAAATGACAGTACCGTAAGAATAAGGTCCGGCTAAATACGTGCCAGCAGCCGCGG
TAATACGTATGGACCGAGCGTTGTCCGGAATCATTGGGCGTAAAGGGTACGTAGGCGGCCTAGTAAGTTA
GAAGTTAAAGAATATAGCTCAACTATATAAAGCTTTTAAAACTGCTAGGCTTGAGAGATGGAAGGGAAAG
TGGAATTCCTAGTGTAGCGGTGAAATGCGCAGATATTAGGAAGAATACCGGTGGCGAAGGCGACTTTCTG
GTCATCATCTGACGCTGAGGTACGAAAGCGTGGGTAGCAAACAGGATTAGATACCCTGGTAGTCCACGCT
GTAAACGATGAGTGTTAGGTTCTTGGAATAATCTGGGAGCCGCAGCTAACGCATTAAACACTCCGCCTGG
GGAGTACGCACGCAAGTGTGAAACTCAAAGGAATTGACGGGGACCCGCACAAGCAGCGGAGCATGTGGTT
TAATTCGACGCAACGCGAAGAACCTTACCAAGTCTTGACATATTTCGGAGGGAATTAGAGATAATTCCTT
ACGACTTCGGTCGACTGAAATACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTA
AGTCCCATAACGAGCGCAACCCCTATCGTTAGTTACCATCATTAAGTTGGGGACTCTAGCGATACTGCCG
GTGATAAACCGGAGGAAGGTGGGGACGACGTCAAATCATCATGCCCTTTATGACTTGGGCTACACACGTG
CTACAATGGCAGATACAGAGGGCAGCGAAAGAGTGATCTGAAGCGAAACTCACAAAATCTGTCCCAGTTC
GGATTGTACTCTGCAACTCGAGTACATGAAGTTGGAGTTGCTAGTAATCGCGAATCAGAATGTCGCGGTG
AATGCGAACCCGGGTCT
>gi|643422283|gb|KF101955.1| Uncultured bacterium clone ncd2798a01c1 16S ribosomal RNA gene, partial sequence
GATGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGAAGCATTTGCGACAGATTTCTTCGGGATG
AAGTTGCTTATGACTGAGTGGCGGACGGGTGAGTAACGCGTGGGTAACCTGCCTTGTACTGGGGGATAGC
AGCTGGAAACGGCTGGTAATACCGCATAAGCGCACAATGTTGCATGACATGGTGTGAAAAACTCCGGTGG
TATAAGATGGACCCGCGTCTGATTAGCTAGTTGGTGAGATAACAGCCCACCAAGGCGACGATCAGTAGCC
GACCTGAGAGGGTGACCGGCCACATTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGG
GAATATTGCACAATGGAGGAAACTCTGATGCAGCGACGCCGCGTGAGTGAAGAAGTAATTCGTTATGTAA
AGCTCTATCAGCAGGGAAGATAGTGACGGTACCTGACTAAGAAGCTCCGGCTAAATACGTGCCAGCAGCC
GCGGTAATACGTATGGAGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGTGTAGGTGGCCATGCAA
GTCAGAAGTGAAAATCCGGGGCTCAACCCCGGAACTGCTTTTGAAACTGTAAGGCTGGAGTGCAGGAGGG
GTGAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCT
CACTGGACTGTAACTGACACTGAGGCTCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCC
ACGCCGTAAACGATGAATACTAGGTGTCGGGGCCCATAAGGGCTTCGGTGCCGCAGCAAACGCAATAAGT
ATTCCACCTGGGGAGTACGTTCGCAAGAATGAAACTCAAAGGAATTGACGGGGACCCGCACAAGCGGTGG
AGCATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCAAGTCTTGACATCCCACTGACCGGACAGTA
ATGTGTCCTTTCCTTCGGGACAGTGGAGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGT
TGGGTTAAGTCCTGCAACGAGCGCAACCCCTATCCTTAGTAGCCAGCAGTAAGATGGGCACTCTAGGGAG
ACTGCCAGGGATAACCTGGAGGAAGGTGGGGATGACGTCAAATCATCATGCCCCTTATGACTTGGGCTAC
ACACGTGCTACAATGGCGTAAACAAAGTGAAGCGAAGTCGTGAGGCCAAGCAAATCACAAAAATAACGTC
TCAGTTCGGATTGTAGTCTGCAACTCGACTACATGAAGCTGGAATCGCTAGTAATCGCAGATCAGAATGC
TGCGGTGAATACGTTCCCGGGTCT
>gi|676402758|gb|KM043769.1| Bacterium P1C6 16S ribosomal RNA gene, partial sequence
GCGGATTTCTTCGGATTGAAGCCTTTGTGACTGAGCGGCGGACGGGTGAGTAACGCGTGGGTAACCTGCC
TCATACAGGGGGATAACAGTTGGAAACGGCTGCTAATACCGCATAAGCGCACAGTACCGCATGGTACGGT
GTGAAAAACTCCGGTGGTATGAGATGGACCCGCGTCTGATTAGGTAGTTGGTGGGGTAACGGCCTACCAA
GCCGACGATCAGTAGCCGACCTGAGAGGGTGACCGGCCACATTGGGACTGAGACACGGCCCAAACTCCTA
CGGGAGGCAGCAGTGGGGAATATTGCACAATGGGGGAAACCCTGATGCAGCGACGCCGCGTGAGCGATGA
AGTATTTCGGTATGTAAAGCTCTATCAGCAGGGAAGAAAATGACGGTACCTGACTAAGAAGCCCCGGCTA
ACTACGTGCCAGCAGCCGCGGTAATACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG
CGTAGACGGCATGGCAAGCCAGATGTGAAAGCCCGGGGCTCAACCCCGGGACTGCATTTGGAACTGTCAG
GCTAGAGTGTCGGAGAGGAAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACAC
CAGTGGCGAAGGCGGCTTTCTGGACGATGACTGACGTTGAGGCTCGAAAGCGTGGGGAGCAAACAGGATT
AGATACCCTGGTAGTCCACGCCGTAAACGATGAATACTAGGTGTCGGGTGGCAAAGCCATTCGGTGCCGC
AGCAAACGCAATAAGTATTCCACCTGGGGAGTACGTTCGCAAGAATGAAACTCAAAGGAATTGACGGGGA
CCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCTGGTCTTGACATCC
CTCTGACCGCTCTTTAATCGGAGCTTTCCTTCGGGACAGAGGAGACAGGTGGTGCATGGTTGTCGTCAGC
TCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTATCTTTAGTAGCCAGCATT
>gi|657358016|dbj|AB940214.1| Uncultured prokaryote gene for 16S rRNA, partial sequence, clone: NNCTHY1886
ACGTAGGGAGCGAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGCGAGGCAAGTCAGGCG
TGAAATCTATGGGCTTAACCCATAAACTGCGCTTGAAACTGTCTTGCTTGAGTGAAGTAGAGGTAGGCGG
AATTCCCGGTGTAGCGGTGAAATGCGTAGAGATCGGGAGGAACACCAGTGGCGAAGGCGGCCTACTGGGC
TTTAACTGACGCTGAAGCACGAAAGCATGGGTAGCAAACAG
>gi|240006380|gb|GQ159538.1| Uncultured bacterium clone 16slp110-1c01.p1k 16S ribosomal RNA gene, partial sequence
GCTCAGGATGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAGCGAAGCGCTTAAGTTTGATTCTTCG
GATGAGTGACTGAGCGGCGGACGGGTGAGTAACGCGTGGGTAACCTGCCTCATACAGGGGGATAACAGTT
AGAAATGACTGCTAATACCGCATAAGACCACGGTACCGCATGGTACAGTGGTAAAAACTCTGGTGGTATG
AGATGGACCCGCGTCTGATTAGGTAGTTGGTGGGGTAACGGCCTACCAAGCCGACGATCAGTAGCCGACC
TGAGAGGGTGACCGGCCACATTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGAAT
ATTGCACAATGGAGGAAACTCTGATGCAGCGACGCCGCGTGAAGGATGAAGTATTTCGGTATGTAAACTT
CTATCAGCAGGGAAGAAAATGACGGTACCTGACTAAGAAGCCCCGGCTAACTACGTGCCAGCAGCCGCGG
TAATACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCACGGCAAGCCA
GATGTGAAAGCCCGGGGCTCAACCCCGGGACTGCATTTGGAACTGCTGAGCTAGAGTGTCGGAGAGGCAA
GTAGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCTTGCT
GGACGATGACTGACGTTGAGGCTCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGC
CGTAAACGATGACTGCTAGGTGTCGGGTGGCAAAGCCATTCGGTGCCGCAGCTAACGCAATAAGCAGTCC
ACCTGGGGAGTACGTTCGCAAGAATGAAACTCAAAGGAATTGACGGGGACCCGCACAAGCGGTGGAGCAT
GTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCTGATCTTGACATCCCGATGACCGCTTCGTAATGGA
AGCTTTTCTTCGGAACATCGGTGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGT
TAAGTCCCGCAACGAGCGCAACCCCTATCTTCAGTAGCCAGCAGGTTAAGCTGGGCACTCTGGAGAGACT
GCCAGGGATAACCTGGAGGAAGGTGGGGATGACGTCAAATCATCATGCCCCTTATGACCAGGGCTACACA
CGTGCTACAATGGCGTAAACAAAGAGAAGCAAACTCGCGAGGGTAAGCAAATCTCAAAAATAACGTCTCA
GTTCGGATTGTAGTCTGCAACTCGACTACATGAAGCTGGAATCGCTAGTAATCGCAGATCAGAATGCTGC
GGTGAATACGTTCCCGGGTCTTGTACACACCGCCCGTCACACCATGGGAGTCAGTAACGCCCGAAGTCAG
TGACCCAACTGTAAGCGGATGCTGCCGAAGGTGGGACCGATATCTGGGAAGGAGTCGTAACAAGGTAGCC
GT
"""

chimera_db_18S = """
"""

if __name__ == '__main__':
    main()